#!/usr/bin/env dash

# Config by:
#   ____                            _    _         _             _    _
#  / ___|_ __ ___  _ __  _   _     / \  | | ____ _| |_ ___ _   _| | _(_)
# | |   | '__/ _ \| '_ \| | | |   / _ \ | |/ / _` | __/ __| | | | |/ / |
# | |___| | | (_) | | | | |_| |  / ___ \|   < (_| | |_\__ \ |_| |   <| |
#  \____|_|  \___/|_| |_|\__, | /_/   \_\_|\_\__,_|\__|___/\__,_|_|\_\_|
#                        |___/

#---BSPWM Bindings---#

# Quit bspwm
super + shift + e
    rofi -show power-menu -modi power-menu:power-menu -show-icons -font "hack 10" -lines 2 -width 11

# Restart bspwm
super + shift + r
    bspc wm -r

# Close Window
super + shift + q
    xdo close

# Kill Window
ctrl + alt + Escape
    xkill

# Focus on window in direction
super + {Left,Down,Up,Right}
	bspc node -f {west,south,north,east}

#	Send window to desktop
super + shift + {1-9}
    bspc node -d {1-9} 

# Toggle floating on and off
super + +shift + space
    bspc node focused.tiled -t floating || bspc node focused.floating -t tiled

# Swap window with direction
super + shift + {Left,Down,Up,Right}
	bspc node -s {west,south,north,east}

# Focus on desktop
super + {1-9}
	bspc desktop -f {1-9}

# Cycle trought windows/workspaces
{super,alt} + {_,shift +} space
	bspc {desktop,node} -f {next,prev}.local

# Last used workspace/window
{super,alt} + Tab
	bspc {desktop,node} -f last

# Fullscreen toggle
super + F11
    bspc node -t \~fullscreen

#---System Control---#

# Lock the screen
super + shift + l
    betterlockscreen -l dimblur

# Audio Control
{XF86AudioRaiseVolume,XF86AudioLowerVolume,XF86AudioMute}
    pamixer {-i 2, -d 2, --toggle} && polybar-msg hook volume 1

# Brightness
{XF86MonBrightnessUp,XF86MonBrightnessDown}
    light {-A 5, -U 5} && polybar-msg hook backlight 1

# Quick resolution change beetween 1366x768 and 640x480
super + {ctrl ,shift} + 0
    {xrandr --output eDP --mode 1366x768 ,xrandr --output eDP --mode 640x480}

# System look control
super + {ctrl,shift} + F12
    {cluter.sh ,clean.sh}

# Screenshots using scrot
Print
    scrot -q 100 -p '%d-%m-%Y_%H:%M:%S_$wx$h_scrot.png' -e 'mv $f ~/Pictures/screenshots'

# mpd control keybindings
{XF86AudioPlay,XF86AudioStop,XF86AudioPrev,XF86AudioNext}
    mpc {toggle,stop,prev,next} && polybar-msg hook mpd-status 1

# turn on floating mode on desktop 4
super + {ctrl, shift} + F11
    {killall floating.sh ,floating.sh}
#---Application Launchers---#

# run rofi
super + d
    rofi -modi drun -show drun -show-icons -display-drun "" -font "hack 10" -lines 15 -width 30

# run my gui programs
super + {Return,b,t,g,r}
    {$TERMINAL,$BROWSER,trackma-qt,lutris,retroarch}

# terminal programs
super + {m,f,w,h,e,k,n}
    $TERMINAL -e {ncmpcpp,lf,adl,htop,$EDITOR,calcurse,newsboat}

# some more programs
super + shift + {f,c,s}
    {pcmanfm,stacer,steam}

# run cli programs
super + shift + {w ,t,n}
    $TERMINAL -e {adl -d ,tremc,joplin}

# system programs
super + ctrl + {f}
    {gparted}

# ffmpeg recording without audio
super + KP_Subtract     
    desktop-rec

# ffmpeg recording with audio
super + shift + KP_Subtract
    game-rec

# stop ffmpeg recording
super + ctrl + KP_Subtract
    killall ffmpeg -INT
