#!/usr/bin/env dash

#---BSPWM Bindings---#

# Quit bspwm
super + shift + e
    rofi -show power-menu -modi power-menu:power-menu -show-icons -font "hack 10" -lines 2 -width 11

# Restart bspwm
super + shift + r
    bspc wm -r

# Close Window
super + shift + q
    xdo close

# Kill Window
ctrl + alt + Escape
    xkill

# Focus on window in direction
super + {Left,Down,Up,Right}
	bspc node -f {west,south,north,east}

#	Send window to desktop
super + shift + {1-9}
    bspc node -d {1-9}

# Toggle floating on and off
super + +shift + space
    bspc node focused.tiled -t floating || bspc node focused.floating -t tiled

# Swap window with direction
super + shift + {Left,Down,Up,Right}
	bspc node -s {west,south,north,east}

# Focus on desktop
super + {1-9}
	bspc desktop -f {1-9}

# Cycle trought windows/workspaces
{super,alt} + {_,shift +} space
	bspc {desktop,node} -f {next,prev}.local

# Last used workspace/window
{super,alt} + Tab
	bspc {desktop,node} -f last

# Rotate all windows {counter-}clockwise by 90 degrees.
mod3 + {_,shift + }r
	bspc node @/ --rotate {90,-90}

# Fullscreen toggle
super + F11
    bspc node -t \~fullscreen

#---System Control---#

# Lock the screen
super + shift + l
    betterlockscreen -l dimblur

# Audio Control
{XF86AudioRaiseVolume,XF86AudioLowerVolume,XF86AudioMute}
    pamixer {-i 2, -d 2, --toggle} && polybar-msg hook volume 1

# Brightness
{XF86MonBrightnessUp,XF86MonBrightnessDown}
    light {-A 10, -U 10} && polybar-msg hook backlight 1

# Quick resolution change beetween 1366x768 and 640x480
super + {ctrl ,shift} + 0
    {xrandr --output eDP --mode 1366x768 ,xrandr --output eDP --mode 640x480}

# Compositor control
super + {ctrl,shift} + F12
    {picom ,killall picom}

# System bar control control
super + {ctrl,shift} + F11
    {polybar -r top ,killall polybar}

# Screenshots using scrot
Print
    scrot -q 100 -p '%d-%m-%Y_%H:%M:%S_$wx$h_scrot.png' -e 'mv $f ~/Pictures/screenshots'

# mpd control keybindings
{XF86AudioPlay,XF86AudioStop,XF86AudioPrev,XF86AudioNext}
    mpc {toggle,stop,prev,next} && polybar-msg hook mpd-status 1

#---Application Launchers---#

# run rofi
super + d
    rofi -modi drun -show drun -show-icons -display-drun "" -font "hack 10" -lines 15 -width 30

# run my gui programs
super + {Return,b,t,v}
    {$TERMINAL,$BROWSER,trackma-qt,$VISUAL}

# terminal programs
super + {m,f,p,w,h,e}
    $TERMINAL -e {ncmpcpp,lf,pacui,adl,htop,$EDITOR}

# some more programs
super + shift + {f,c,s,d,g}
    {pcmanfm,stacer,steam,discord,lutris}

# run cli programs
super + shift + {w ,t}
    $TERMINAL -e {adl -d ,tremc}

# system programs
super + ctrl + f
    gparted

# ffmpeg recording without audio
super + KP_Subtract     
    desktop-rec

# ffmpeg recording with audio
super + shift + KP_Subtract
    game-rec

# stop ffmpeg recording
super + ctrl + KP_Subtract
    killall ffmpeg -INT
