#!/bin/dash
# change it to #!/bin/sh if you are on debian based distro
  # ____                            _    _         _             _    _
 # / ___|_ __ ___  _ __  _   _     / \  | | ____ _| |_ ___ _   _| | _(_)
# | |   | '__/ _ \| '_ \| | | |   / _ \ | |/ / _` | __/ __| | | | |/ / |
# | |___| | | (_) | | | | |_| |  / ___ \|   < (_| | |_\__ \ |_| |   <| |
 # \____|_|  \___/|_| |_|\__, | /_/   \_\_|\_\__,_|\__|___/\__,_|_|\_\_|
                       # |___/

###---MONITORS---###
bspc monitor -d 1 2 3 4 5 6 7 8 9
###---Autostart---###
autostart.sh

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

###---Coloring---###
bspc config normal_border_color	"#32302f"
bspc config active_border_color	"#282828"
bspc config focused_border_color "#a89984"
bspc config presel_feedback_color	"#ebdbb2"
bspc config urgent_border_color "#cc241d'"

###---Monitor And Desktop Settings----###
bspc config top_padding 20
bspc config bottom_padding 20
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 1
bspc config window_gap 5

###---Rules---###
bspc rule -a mpv state=fullscreen 
bspc rule -a Zathura state=fullscreen
bspc rule -a Foliate state=fullscreen
bspc rule -a Lutris desktop=^4 follow=on
bspc rule -a Steam desktop=^4 follow=on
